server:
  port: 8080
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: K50471982k
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource


    hikari:
      maximum-pool-size: 10
      connection-timeout: 120000
      max-lifetime: 120000
      minimum-idle: 4

  liquibase:
    enabled: false
    change-log: db/changelog/master.xml

  jpa:
    open-in-view: false

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*.xml

logging:
  level:
    com.spring.ibatis: DEBUG