DROP SEQUENCE IF EXISTS nomenclature_seq;
DROP SEQUENCE IF EXISTS product_seq;
DROP SEQUENCE IF EXISTS product_type_seq;
DROP SEQUENCE IF EXISTS log_seq;
DROP SEQUENCE IF EXISTS shopping_seq;
DROP SEQUENCE IF EXISTS profit_seq;
DROP SEQUENCE IF EXISTS person_data_seq;
